PDManagerWeb/Controllers/FrontController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace PDManagerWeb.Controllers
{
    [Route("")]
    public class FrontController : Controller
    {
        public FrontController()
        {
        }

        [HttpGet("")]
        public IActionResult Auth()
        {
            if (HttpContext.Session.GetInt32("id") == null)
                return View();
            return Redirect("/Documents");
        }

        [HttpGet("Documents")]
        public IActionResult Documents()
        {
            if (HttpContext.Session.GetInt32("id") == null)
                return Redirect("/");
            return View();
        }

        [HttpGet("Admin")]
        public IActionResult Admin()
        {
            if (HttpContext.Session.GetInt32("id") == null)
                return Redirect("/");
            return View();
        }

        [HttpGet("DeAuth")]
        public IActionResult DeAuth()
        {
            HttpContext.Session.Remove("id");
            return Redirect("/");
        }
    }
}

PDManagerWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PDManagerWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PDManagerWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Front" asp-action="Auth">PDManagerWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Front" asp-action="Documents">Документация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Front" asp-action="Admin">Администрирование</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Front" asp-action="DeAuth">Выход</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            2024 - PDManagerWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>